### ISSUE TITLE
No module named rl_bot

### ISSUE THREAD

**Issue by kaanap** [AgrawalAmey/rl-car#1]
Hi,
It seems like it cannot find rl_bot and when I try to run the code I get this eror:
Traceback (most recent call last):
  File "/Users/kaanapaydin/anaconda3/envs/VREP/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/kaanapaydin/anaconda3/envs/VREP/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/kaanapaydin/Desktop/rl-car-master/rl_car/proximity_sensor/train.py", line 9, in <module>
    from .env import RLCar
  File "/Users/kaanapaydin/Desktop/rl-car-master/rl_car/proximity_sensor/env.py", line 9, in <module>
    from rl_bot.vrep import vrep
ModuleNotFoundError: No module named 'rl_bot'

**Comment by AgrawalAmey** [comment]
Sorry, looks like an issue introduced during recent refactoring. I have pushed the fixed. Sorry for inconviniance, please let know if you hit any other issues.

**Comment by kaanap** [comment]
Works Like A Charm Thank You
